### ISSUE TITLE
Minds Go SDK

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/minds_python_sdk#19]
### Short description of current behavior

The goal of this issue is to develop a new Golang SDK for Minds.

## Steps :male_detective: :female_detective: 
 
-  You can familiarize yourself with [Minds](https://mindsdb.com/).
-  Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
-  Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
-  Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.

## :loudspeaker: Additional rewards :trophy:

This issue brings :one: :two: :zero: points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x: :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by Abiji-2020** [comment]
- We need to create a new repo and link the github link of the new repo in readme with a new section as other SDK and request a PR ?

**Comment by Zedoman** [comment]
Sir please assign this to me as i have made this project using go.

**Comment by ashish111333** [comment]
@ZoranPandovski  hey I would like to work on this.

**Comment by Zedoman** [comment]
@ZoranPandovski sir can you please check my PR for the minds GO SDK i have created one.

**Comment by Shr11** [comment]
Hello, I'm currently going through the python sdk and planning to build one in JS/GO. Please assign this issue to me, I'll give it my best!

**Comment by ZoranPandovski** [comment]
Please make sure you are reading the description:
```
Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.
```

**Comment by Abiji-2020** [comment]
@ZoranPandovski We just need to add the `external repository link` in the Readme.md file as other sdk right ?

**Comment by Abiji-2020** [comment]
@quest-bot embark

**Comment by Rupeshprajapati2123** [comment]
@quest-bot embark
