### ISSUE TITLE
Minds Dart SDK

### ISSUE THREAD

**Issue by chandrevdw31** [mindsdb/minds_python_sdk#20]
## Short description of current behavior

The goal of this issue is to develop a new Dart SDK for Minds.

## Steps 🕵️‍♂️ 🕵️‍♀️

- You can familiarize yourself with [Minds](https://mindsdb.com/).
- Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
- Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
- Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.

## 📢 Additional rewards 🏆
This issue brings 1️⃣ 2️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

-  3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
- ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by priyanshuverma-dev** [comment]
@chandrevdw31 I am in working on this issue

**Comment by Sekhar-Kumar-Dash** [comment]
@chandrevdw31  i would like to work on this issue too

**Comment by priyanshuverma-dev** [comment]
Hi @chandrevdw31,
I have created Dart SDK.
before making PR, I would like to show you so that you can guide if anything is remaining to do as I don't want to lose any chance.

Repo: https://github.com/priyanshuverma-dev/minds_sdk

**Comment by chandrevdw31** [comment]
@priyanshuverma-dev you need to submit it via Quira https://quira.sh/quests/creator/details?questId=22
@ZoranPandovski please have a look

**Comment by priyanshuverma-dev** [comment]
@quest-bot embark

**Comment by ArnavK-09** [comment]
🎯  Here's my submission:- **https://github.com/ArnavK-09/mdb_dart**
