### ISSUE TITLE
Minds Java SDK

### ISSUE THREAD

**Issue by Better-Boy** [mindsdb/minds_python_sdk#23]
## Short description of current behavior

The goal of this issue is to develop a new Java SDK for Minds.

## Steps 🕵️‍♂️ 🕵️‍♀️

- You can familiarize yourself with [Minds](https://mindsdb.com/).
- Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
- Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
- Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.

## 📢 Additional rewards 🏆

This issue brings 1️⃣ 2️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by Better-Boy** [comment]
I already had created an issue for mindsdb repo - https://github.com/mindsdb/mindsdb/issues/9790 which I'm assigned to and working on.
The issue is same. Hence, requesting to be assigned to this issue.

**Comment by Better-Boy** [comment]
Since this needs a separate repo, minds-java-sdk - https://github.com/Better-Boy/minds-java-sdk.

**Comment by ZoranPandovski** [comment]
@Better-Boy Since you already made some progress, I will assign this to you. @chandrevdw31 Will send you an API key on slack

**Comment by Better-Boy** [comment]
@ZoranPandovski I'm done with the java sdk.  Please review once.

The following are done:
1. All functionalities except chat completion are done - (reason - no official java sdk from openai)
2. Unit test done
3. Integration test done
4. Documentation done
5. Readme update

Open to any feedback

**Comment by Better-Boy** [comment]
@quest-bot embark
