### ISSUE TITLE
Minds C# SDK

### ISSUE THREAD

**Issue by Yordaniss** [mindsdb/minds_python_sdk#25]
Short description of current behavior
The goal of this issue is to develop a new C# SDK for Minds.

Steps 🕵️‍♂️ 🕵️‍♀️
You can familiarize yourself with [Minds](https://mindsdb.com/).
Review the existing [Python SDK](https://github.com/mindsdb/minds_python_sdk) as a reference.
Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new SDK to the Other SDKs section of the README.
Multiple contributors are welcome, but the SDK with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.
📢 Additional rewards 🏆
This issue brings 1️⃣ 2️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by Yordaniss** [comment]
Hey @ZoranPandovski

I would like to work on this issue ^^

**Comment by chandrevdw31** [comment]
@Yordaniss you can go ahead and work on the issue, multiple contributors can work on it so we won't be assigning anyone to it

**Comment by Niharika0104** [comment]
@quest-bot embark

**Comment by priyanshuverma-dev** [comment]
@quest-bot embark

**Comment by chandrevdw31** [comment]
@Yordaniss did you make any progress on this?

**Comment by Yordaniss** [comment]
@chandrevdw31 Hello

Unfortunately I did not have so much time to work on this one. I already started but not sure if I will finish my work until 31.10
