### ISSUE TITLE
[Enhancement] ToString representation of minds object

### ISSUE THREAD

**Issue by Better-Boy** [mindsdb/minds_python_sdk#27]
## Short description of current behavior

Currently, Mind object doesn't have a string representation of it's variable value when the object is printed. Instead the object address is printed.

## Steps 🕵️‍♂️ 🕵️‍♀️

- Add a tostring representation of the Mind object where the object variable values are printed. 
- print(mind_obj), str(mind_obj) or just entering the mind_obj in python console should print the object variable values.

## 📢 Additional rewards 🏆

This issue brings 5️⃣ 0️⃣ points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by ZoranPandovski** [comment]
@Better-Boy Note that the issue points are rewarded by the MindsDB team, not by the contributor
