### ISSUE TITLE
Improve Minds name requirements

### ISSUE THREAD

**Issue by chandrevdw31** [mindsdb/minds_python_sdk#30]
## Short description of current behavior
Improve the name requirements for minds

## Steps 🕵️‍♂️ 🕵️‍♀️
- Add name requirements.
- Mind name should start with a letter and contain only letters, numbers or underscore, with a maximum of 32 characters. Spaces are not allowed.

## 📢 Additional rewards 🏆
This issue brings 4️⃣ 0️⃣  points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by Better-Boy** [comment]
I want to work on this
