### ISSUE TITLE
Minds CLI

### ISSUE THREAD

**Issue by chandrevdw31** [mindsdb/minds_python_sdk#33]
## Short description of current behavior
The goal of this issue is to develop a new CLI for Minds.

## Steps 🕵️‍♂️ 🕵️‍♀️
- You can familiarize yourself with [Minds](https://mindsdb.com/).

- Create a new repository in your account and submit a Pull Request (PR) to this repository, adding the new CLI to the Other SDKs section of the README.
- Multiple contributors are welcome, but the CLI with the highest standards—such as clear documentation, robust tests, and overall code quality—will be accepted.

## 📢 Additional rewards 🏆
This issue brings 1️⃣ 0️⃣  0️⃣ points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by Better-Boy** [comment]
I want to work on this

**Comment by ashish111333** [comment]
does the cli needs to be in python ? or any language of our choice ? @chandrevdw31

**Comment by Better-Boy** [comment]
> does the cli needs to be in python or any language of our choice ? @chandrevdw31

The language of choice shouldn't matter in my opinion. Since, python sdk is maintained by the mindsdb team, I went ahead with python.

**Comment by Better-Boy** [comment]
@quest-bot embark

**Comment by naaa760** [comment]
I want to work on this issue!
