### ISSUE TITLE
OpenAI client enhancement

### ISSUE THREAD

**Issue by chandrevdw31** [mindsdb/minds_python_sdk#42]
## Short description of current behavior
The goal of this issue is to add code to create the client once and reuse during multiple chat completion queries

## Steps 🕵️‍♂️ 🕵️‍♀️
- You can familiarize yourself with [Minds](https://mindsdb.com/).

- Create Pull Request to this repo.

## 📢 Additional rewards 🏆
This issue brings 1️⃣ 0️⃣  points for SWAG and entry into the draw for a 👇 :

3️⃣ ❌ 💻 [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
👕 🐻 [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
ℹ️ For more info check out https://mindsdb.com/hacktoberfest 👈

**Comment by Shr11** [comment]
I'd like to work on this!
