### ISSUE TITLE
[Enhancement] Datasource name validation

### ISSUE THREAD

**Issue by Better-Boy** [mindsdb/minds_python_sdk#46]
Currently, an API call is made when creating a datasource without any validation on the name.  The response is as follows:

```
minds.exceptions.UnknownError: Bad Request: {"title": "Wrong name", "detail": "The name \"my-datasource\" does not meet requirements", "timestamp": "2024-10-23 00:49:03.760930"}
```

1. When creating/updating a datasource, we can validate the name before making an API call. Hence, saving an API call.
2. The requirements for datasource name are not mentioned in the exception message.

**Comment by Better-Boy** [comment]
I want to work on this.

@ea-rus what are the requirements for a valid datasource name?

**Comment by ea-rus** [comment]
It is checked with regexp '^[a-zA-Z][a-zA-Z0-9_]*$'

**Comment by Better-Boy** [comment]
> It is checked with regexp '^[a-zA-Z][a-zA-Z0-9_]*$'

Can I add this feature?

**Comment by ea-rus** [comment]
I think yes, it can be useful

**Comment by Better-Boy** [comment]
> It is checked with regexp '^[a-zA-Z][a-zA-Z0-9_]*$'

According to the regex, name can be of any length. Shouldn't we restrict this to 16 or 32?

**Comment by ea-rus** [comment]
Forgot about the length, max length is 62
